### PR TITLE
Feature data tests

### PR DESCRIPTION
**Pull request by JanStoltman**
Tests for most of the data package were created. WeatherOfflineInterceptor was left out as creating tests for it is a little bit tricky so I will push it in separate branch once I figure it out (Perhaps together with tests for the new cache interceptor)

### CODE REVIEW

**Comment by sphrak** [comment]
@JanStoltman you are doing gods work here :+1: good job. forgot to mention, please consider adding urself to https://github.com/vadret/android/blob/dev/CONTRIBUTORS -- if you want ofc. gotta give credit where credit is due u know.

I have setup codecov but for some reason the badge doesnt update the percentage, it only picked up the feature branches and the dev one, but not master.. weird. Ill merge this right away.

**Comment by sphrak** [comment]
https://github.com/vadret/android/commit/5de324b94f839c746080e79d8405e626c4ad4358

**Comment by JanStoltman** [comment]
@sphrak After setting up codecov you have to commit something to a branch for codecov to pick that branch for check

**Comment by sphrak** [comment]
closing since merged now

**Pull request closed without merging**
