### PR TITLE
Fix/issue29

### PR DESCRIPTION
**Pull request by Z3nk**
relative to #29

### CODE REVIEW

**Comment by sphrak** [comment]
@Z3nk Thank you for your contribution. But why are there two PRs though? This PR seems to touch both `no`, `dk` and `fr`? whereas the other one is `fr` and `no`.

**Comment by Z3nk** [comment]
Hi, it's fixed. 
I had branch fix/issue29 create from fix/issue28, that's why i got modification of both branch.
Now, fix/issue29 is standealone.

**Comment by Z3nk** [comment]
#45 have Norway translate, this one (#46) have french and danish translate

**Comment by sphrak** [comment]
I guess you mean the opposite, but its fine again thank you. I will merge it asap

**Comment by sphrak** [comment]
Again thank you for your contribution, it has now been merged.

**Pull request merged**
