### PR TITLE
fixes #86 -- build fails on missing .env

### LINKED ISSUE #86: Error during build
Hello,

When trying to build 0.1.2 with `./gradlew assemble`, I get the following error:
```
Execution failed for task ':app:processFdroidDebugManifest'.
> java.lang.NullPointerException (no error message)
```

Here is the full log: https://gist.github.com/Rudloff/c2ce9f9d83c06d20f8032eb4d18e1a94

I'm getting this error with any variant.
Do I need to add something to my `.env` file maybe?

### PR DESCRIPTION
**Pull request by sphrak**

### CODE REVIEW

**Comment by Rudloff** [comment]
I confirm, it now builds correctly, thanks!

**Comment by sphrak** [comment]
@Rudloff Even the signing part on your end? :-)

**Comment by Rudloff** [comment]
Yes, `assembleFdroidRelease` generates an unsigned APK, which is exactly what we need.

**Comment by sphrak** [comment]
Splendid, thank you mate :octocat:

**Pull request merged**
