### PR TITLE
Weather use case tests

### PR DESCRIPTION
**Pull request by JanStoltman**
There is a little bit of copied code, in future it might be reasonable to create Util class for tests

### CODE REVIEW

**Comment by sphrak** [comment]
@JanStoltman I squashed and merged the other commit into dev, however this now has merge conflicts. Either you fix it, or you tell me which of the conflicting items to keep and ill fix it :)

**Comment by JanStoltman** [comment]
@sphrak I will take care of it

**Comment by sphrak** [comment]
@JanStoltman I think you can install ktlint as a githook so you dont forget it before you push to remote :-)

**Comment by JanStoltman** [comment]
@sphrak I've fixed this from browser so auto code formatting didn't pick it up I'm afraid. I will fix it soon and push again, third time will be a charm I hope ;)

**Comment by sphrak** [comment]
@JanStoltman oh I see, hacking-on-the-fly I see ;) 
squashed and merged https://github.com/vadret/android/commit/926b9e2142f1d5d1baad2fc3e26c2e64ad6aae74

**Pull request closed without merging**
