### PR TITLE
Weather VM unit tests

### PR DESCRIPTION
**Pull request by JanStoltman**
Unit tests for WeatherViewModel have been created and inline rule for MockMaker has been added

### CODE REVIEW

**Comment by sphrak** [comment]
@JanStoltman looks good, however since no tests existed before the tests arent picked up by travis -- so could you add `- "./gradlew test"` to `.travis.yml`?

**Comment by JanStoltman** [comment]
@sphrak Sure, done

**Comment by JanStoltman** [comment]
@sphrak I've set up Travins on my fork and tested it. Tests results aren't visible in logs but if any of the tests fails, the whole build fails.

**Comment by sphrak** [comment]
@JanStoltman damn thats awesome, I will merge these two tests a little later then :-) im currently working on a cache interceptor.

**Comment by sphrak** [comment]
https://github.com/vadret/android/commit/1c5d056debd6be3b66b1ff49e409d98347986a3c

**Pull request closed without merging**
